// Generated from the therapy lexicon (pure data, no code). Edit the source lists, not this file by hand.
// Keywords are lower-case; single words match stemmed tokens, phrases match the sentence text.
const Lexicon = {
 "themes": [
  {
   "name": "Anxiety & worry",
   "keywords": [
    "anxiety",
    "anxious",
    "worry",
    "worried",
    "worrying",
    "panic",
    "nervous",
    "stress",
    "stressed",
    "dread",
    "fear",
    "scared",
    "overthink",
    "overthinking",
    "ruminate",
    "racing thoughts",
    "what if",
    "on edge",
    "can't relax",
    "cant relax",
    "panic attack",
    "heart racing",
    "freaking out",
    "spiral",
    "spiraling",
    "tense",
    "restless",
    "uneasy",
    "jittery",
    "catastrophe"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Set a 15-minute worry window each day",
     "detail": "Pick a fixed time, say 6 pm, and write every worry that shows up during the day on a list to deal with then. When the window arrives, go through the list: decide for each item whether there is one small action you can take, or whether it is out of your hands for now.",
     "rationale": "{theme} came up {n} times in this session, so giving worry a container may free up the rest of the day."
    },
    {
     "category": "practice",
     "title": "Breathe out longer than you breathe in",
     "detail": "When you notice tension rising, breathe in through your nose for a count of four and out through your mouth for a count of six. Repeat for two to three minutes; the long exhale tells your nervous system it can stand down.",
     "rationale": "You described feeling anxious or on edge {n} times; a longer exhale is the quickest way to settle the body."
    },
    {
     "category": "reflection",
     "title": "Write down the worst case, the best case and the most likely case",
     "detail": "Take one worry and write three short lines: what you fear will happen, the best thing that could happen, and what most likely will happen. Then note one thing you would do to cope if the worst case actually arrived.",
     "rationale": "{theme} was a central thread in this session; putting the fear on paper tends to shrink it to its real size."
    }
   ],
   "questions": [
    "Could we look at what makes my anxiety spike at certain times of the day or week?",
    "What is one anxiety tool we could practice together so I can use it when I am alone?",
    "How do I tell the difference between useful worry and the kind that just spins?"
   ]
  },
  {
   "name": "Low mood",
   "keywords": [
    "depressed",
    "depression",
    "sad",
    "sadness",
    "hopeless",
    "empty",
    "numb",
    "low",
    "down",
    "unmotivated",
    "no energy",
    "can't get out of bed",
    "cant get out of bed",
    "nothing matters",
    "pointless",
    "what's the point",
    "whats the point",
    "crying",
    "cry",
    "tearful",
    "flat",
    "heavy",
    "dark",
    "miserable",
    "no joy",
    "don't enjoy",
    "dont enjoy",
    "withdrawn",
    "stuck"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Schedule one small pleasant activity for tomorrow",
     "detail": "Choose something that used to feel good even a little, like a short walk, a favourite song, or a call with a friend, and put it in your calendar at a specific time. Do it whether or not you feel like it; the mood often follows the action rather than the other way round.",
     "rationale": "{theme} came up {n} times in this session. Behavioural activation is one of the most reliable ways to lift it a notch."
    },
    {
     "category": "selfCare",
     "title": "Protect the basics: light, food, movement, people",
     "detail": "Each day this week, aim for ten minutes of daylight, one proper meal, a few minutes of movement, and one short contact with another person. Tick them off on paper; on hard days, two out of four is a win.",
     "rationale": "You talked about feeling low {n} times, and the basics are what keep a low patch from sinking further."
    },
    {
     "category": "reflection",
     "title": "Keep a three-good-things note at bedtime",
     "detail": "Before sleep, write three things that went okay today, however small, and one line about why each happened. This is not about forcing positivity; it trains attention to notice what the low mood filters out.",
     "rationale": "{theme} was a strong thread today; noticing small positives counterbalances the mood's tendency to only register the hard parts."
    }
   ],
   "questions": [
    "Could we map out what a low day looks like for me from morning to night, and where it might be interrupted?",
    "What would be a realistic first step to feel a bit more like myself again?",
    "How do I know when a low patch is something I should take more seriously?"
   ]
  },
  {
   "name": "Sleep",
   "keywords": [
    "sleep",
    "sleeping",
    "insomnia",
    "tired",
    "exhausted",
    "nightmare",
    "nightmares",
    "bed",
    "bedtime",
    "awake",
    "wake up",
    "waking up",
    "can't sleep",
    "cant sleep",
    "wake up at night",
    "lying awake",
    "fall asleep",
    "falling asleep",
    "nap",
    "oversleep",
    "oversleeping",
    "restless night",
    "no sleep",
    "sleepless",
    "rest",
    "fatigue",
    "drained",
    "wired",
    "alarm",
    "snooze",
    "melatonin"
   ],
   "suggestions": [
    {
     "category": "selfCare",
     "title": "Keep the same wake-up time every day this week",
     "detail": "Set one wake-up time, including weekends, and get daylight within half an hour of getting up. Go to bed only when sleepy. A fixed wake time anchors your body clock faster than anything you do at night.",
     "rationale": "{theme} came up {n} times in this session; a steady wake time is the single most effective sleep habit."
    },
    {
     "category": "practice",
     "title": "Get out of bed after 20 minutes of lying awake",
     "detail": "If you cannot sleep or wake and stay awake, get up, keep lights dim, and do something quiet and boring until you feel sleepy again. The goal is to keep the bed linked with sleep rather than with frustration.",
     "rationale": "You mentioned lying awake or poor sleep {n} times; this is the core move from sleep therapy for exactly that."
    },
    {
     "category": "selfCare",
     "title": "Set a caffeine cutoff and a 30-minute wind-down",
     "detail": "Stop caffeine by early afternoon and, in the last half hour before bed, switch off bright screens and do the same calm routine each night: dim lights, a warm drink, a few pages of a book, or some slow stretching.",
     "rationale": "{theme} was an important thread today, and the two hours before bed are where most sleep problems start."
    }
   ],
   "questions": [
    "Could we look at what is going through my head when I lie awake at night?",
    "Is my tiredness mostly about sleep, or is something else draining me?",
    "Would it help to track my sleep for a week and look at the pattern together?"
   ]
  },
  {
   "name": "Work & career",
   "keywords": [
    "work",
    "job",
    "boss",
    "manager",
    "career",
    "office",
    "colleague",
    "coworker",
    "deadline",
    "promotion",
    "burnout",
    "burned out",
    "burnt out",
    "overworked",
    "meeting",
    "project",
    "performance review",
    "fired",
    "laid off",
    "layoff",
    "quit",
    "resign",
    "interview",
    "workload",
    "client",
    "shift",
    "overtime",
    "email",
    "presentation",
    "my team",
    "unemployed",
    "job search"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Write a hard stop time for work and keep it three days this week",
     "detail": "Pick a realistic end time, put it in your calendar, and when it arrives close the laptop, mute work notifications and do one thing that marks the switch, like a short walk or changing clothes. Note how the evening feels compared with usual.",
     "rationale": "{theme} came up {n} times in this session, often around having no clear end to the day."
    },
    {
     "category": "reflection",
     "title": "Sort your work stress into 'mine to change' and 'not mine'",
     "detail": "List the things at work that drain you. Next to each, write whether it is something you control, something you can influence, or something you can only respond to. Spend your energy on the first column and plan how to protect yourself from the third.",
     "rationale": "You talked about work pressure {n} times; separating what you can change from what you cannot is where relief usually starts."
    },
    {
     "category": "nextSession",
     "title": "Bring one specific work situation to unpack",
     "detail": "Choose one recent moment at work that stuck with you, such as a conversation with your manager or a deadline that went badly. Write what happened, what you thought, and what you felt so you can walk through it in detail next time.",
     "rationale": "{theme} was a central thread today; a concrete example gives you and your therapist something solid to work on."
    }
   ],
   "questions": [
    "Could we look at whether my job is the problem or the way I am carrying it?",
    "How do I talk to my manager about my workload without it sounding like a complaint?",
    "What would a sustainable week at work actually look like for me?"
   ]
  },
  {
   "name": "Relationships",
   "keywords": [
    "partner",
    "boyfriend",
    "girlfriend",
    "husband",
    "wife",
    "spouse",
    "relationship",
    "dating",
    "ex",
    "breakup",
    "break up",
    "broke up",
    "divorce",
    "marriage",
    "argue",
    "argument",
    "fight",
    "fighting",
    "trust",
    "cheated",
    "jealous",
    "intimacy",
    "distance",
    "communication",
    "love",
    "affection",
    "commitment",
    "we never talk",
    "he doesn't listen",
    "she doesn't listen",
    "they don't listen",
    "couple",
    "romantic"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Use an 'I feel... when... I need...' sentence in one conversation",
     "detail": "Before raising something with your partner, write one sentence: 'I feel [emotion] when [specific thing happens], and I need [one concrete request].' Say it calmly at a quiet moment, not mid-argument, and then listen to their side without planning your reply.",
     "rationale": "{theme} came up {n} times in this session, with several moments where needs did not get said plainly."
    },
    {
     "category": "practice",
     "title": "Try a 20-minute pause when an argument heats up",
     "detail": "Agree in advance that either of you can call a pause when things escalate. Separate for at least twenty minutes, do something calming rather than rehearsing your case, and come back to the conversation at an agreed time.",
     "rationale": "You described conflict with your partner {n} times; a planned pause stops the moment the body is too activated to listen."
    },
    {
     "category": "reflection",
     "title": "Write what you want from this relationship in five lines",
     "detail": "Without thinking about what is realistic, write five short lines about how you want to feel with this person. Then mark which of those you feel now, sometimes, or rarely. Bring the list to your next session.",
     "rationale": "{theme} was a strong thread today; getting clear on what you want makes the next steps easier to see."
    }
   ],
   "questions": [
    "Could we look at the pattern that keeps repeating in my arguments with my partner?",
    "How do I bring up what I need without it turning into a fight?",
    "Am I staying in this relationship because I want to, or because I am afraid to leave?"
   ]
  },
  {
   "name": "Family",
   "keywords": [
    "mother",
    "mom",
    "mum",
    "father",
    "dad",
    "parents",
    "parent",
    "sister",
    "brother",
    "sibling",
    "family",
    "grandmother",
    "grandfather",
    "grandma",
    "grandpa",
    "aunt",
    "uncle",
    "cousin",
    "in-laws",
    "in laws",
    "mother-in-law",
    "father-in-law",
    "childhood",
    "growing up",
    "when i was a kid",
    "when i was little",
    "my family",
    "home",
    "holiday",
    "family dinner",
    "relatives"
   ],
   "suggestions": [
    {
     "category": "reflection",
     "title": "Write a letter to a family member that you do not send",
     "detail": "Address it to the person who came up most today. Say what you never got to say, what you needed from them, and what you want now. Keep it private; the point is to hear your own side fully, not to deliver it.",
     "rationale": "{theme} came up {n} times in this session, and some of it sounded like things that have waited a long time to be said."
    },
    {
     "category": "practice",
     "title": "Decide your exit plan before the next family visit",
     "detail": "Before you see family, pick a time you will leave, one topic you will not engage with, and one phrase to change the subject, such as 'I would rather not get into that today.' Tell one person you trust about the plan so it feels real.",
     "rationale": "You talked about family {n} times; having a plan in advance keeps old roles from taking over."
    },
    {
     "category": "reflection",
     "title": "Note which family rule you are still following today",
     "detail": "Think of one unspoken rule from your family growing up, like 'don't make a fuss' or 'always be the strong one.' Write down where it still shows up in your week and whether it still serves you.",
     "rationale": "{theme} was a central thread today, and family rules often run quietly in the background of adult life."
    }
   ],
   "questions": [
    "Could we look at how my role in my family growing up still shapes how I act now?",
    "How do I stay connected to my family without losing myself in their expectations?",
    "Is it okay to want distance from a parent, and how would I handle the guilt?"
   ]
  },
  {
   "name": "Self-worth",
   "keywords": [
    "worthless",
    "not good enough",
    "not enough",
    "failure",
    "useless",
    "stupid",
    "inadequate",
    "self-esteem",
    "self esteem",
    "confidence",
    "insecure",
    "impostor",
    "imposter",
    "hate myself",
    "disappointed in myself",
    "i'm a mess",
    "im a mess",
    "perfectionist",
    "perfect",
    "compare myself",
    "comparing myself",
    "critical of myself",
    "self-critical",
    "inner critic",
    "don't deserve",
    "dont deserve",
    "unlovable",
    "ashamed of myself",
    "fraud"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Try a self-compassion break when the inner critic gets loud",
     "detail": "When you catch yourself being harsh, pause and say three things quietly: 'This is a hard moment,' 'Struggling is part of being human,' and 'May I be kind to myself right now.' Put a hand on your chest if that helps it land.",
     "rationale": "{theme} came up {n} times in this session, mostly in the way you spoke about yourself."
    },
    {
     "category": "reflection",
     "title": "Talk to yourself the way you would talk to a friend",
     "detail": "Write down the harshest thing you told yourself this week. Then imagine a close friend said the same thing about themselves, and write exactly what you would say back to them. Read your reply out loud.",
     "rationale": "You judged yourself {n} times today; the friend test exposes how one-sided the inner critic is."
    },
    {
     "category": "practice",
     "title": "Collect evidence for one week",
     "detail": "Pick one belief like 'I am not good enough' and keep a note on your phone. Each day, write one small fact that does not fit the belief, such as a task you finished or a person who was glad to see you. Review the list at the end of the week.",
     "rationale": "{theme} was a central thread today, and beliefs like this survive by ignoring the evidence against them."
    }
   ],
   "questions": [
    "Could we look at where the voice that says I am not good enough first came from?",
    "How do I build confidence that does not depend on other people's approval?",
    "What would change in my week if I believed I was already enough?"
   ]
  },
  {
   "name": "Anger & irritability",
   "keywords": [
    "angry",
    "anger",
    "furious",
    "rage",
    "irritable",
    "irritated",
    "annoyed",
    "snapped",
    "snap",
    "lost my temper",
    "lose my temper",
    "lashed out",
    "yelled",
    "shouted",
    "resentful",
    "resentment",
    "bitter",
    "pissed off",
    "fed up",
    "frustrated",
    "frustrating",
    "short fuse",
    "blew up",
    "boiling",
    "seething",
    "hostile",
    "slammed",
    "road rage"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Catch the body signal before the words come out",
     "detail": "Notice your personal early warning sign of anger, such as a hot face, tight jaw or clenched hands. When it appears, say 'I need a minute,' step away, and take ten slow breaths before deciding what to say. Practise this on small annoyances first.",
     "rationale": "{theme} came up {n} times in this session, including moments where anger arrived faster than you could catch it."
    },
    {
     "category": "reflection",
     "title": "Find the hurt underneath one angry moment",
     "detail": "Take a recent flare-up and write what happened in one line. Then ask: what did I feel just before the anger, and what did I need in that moment? Anger often guards something softer like feeling dismissed, scared or let down.",
     "rationale": "You described anger or irritation {n} times; it tends to ease once the feeling underneath gets named."
    },
    {
     "category": "selfCare",
     "title": "Burn off the charge with movement the same day",
     "detail": "On days when you feel wound up, do something physical for fifteen minutes: a brisk walk, a run, push-ups, or shaking out your arms and legs. Anger leaves adrenaline in the body, and movement clears it faster than stewing.",
     "rationale": "{theme} was a strong thread today, and the body needs somewhere for that energy to go."
    }
   ],
   "questions": [
    "Could we look at what my anger is trying to protect?",
    "How do I express frustration without hurting people I care about?",
    "Why do small things set me off so much more than they used to?"
   ]
  },
  {
   "name": "Grief & loss",
   "keywords": [
    "grief",
    "grieving",
    "loss",
    "lost",
    "died",
    "death",
    "passed away",
    "funeral",
    "mourning",
    "miss him",
    "miss her",
    "miss them",
    "anniversary",
    "gone",
    "widow",
    "widower",
    "bereaved",
    "memorial",
    "cemetery",
    "ashes",
    "goodbye",
    "cancer",
    "hospice",
    "miscarriage",
    "stillbirth",
    "she died",
    "he died",
    "they died",
    "since she passed",
    "since he passed",
    "left behind"
   ],
   "suggestions": [
    {
     "category": "reflection",
     "title": "Write a letter to the person you lost",
     "detail": "Tell them what has happened since they left, what you miss, and anything that was left unsaid. Write it by hand if you can and keep it somewhere safe. Many people find it helps to continue the relationship in a new form rather than close it.",
     "rationale": "{theme} came up {n} times in this session, and there seemed to be more you wanted to say."
    },
    {
     "category": "selfCare",
     "title": "Plan something gentle around the hard dates",
     "detail": "Look ahead at birthdays, anniversaries and holidays in the next few months. For each, decide in advance how you want to mark it and who you want near you. Having a plan removes the dread of a day arriving unprepared.",
     "rationale": "You spoke about loss {n} times; anniversaries hit hardest when they catch you off guard."
    },
    {
     "category": "practice",
     "title": "Let grief come in waves instead of holding it back all day",
     "detail": "Set aside ten minutes, perhaps with a photo or a song, where you let yourself feel whatever shows up. When the time is over, do something ordinary like making tea. Giving grief a place can make the rest of the day more bearable.",
     "rationale": "{theme} was a central thread today; grief that has nowhere to go tends to leak into everything."
    }
   ],
   "questions": [
    "Could we talk about the guilt I feel about moving on with my life?",
    "Is the way I am grieving normal, or should I be worried about how long it is taking?",
    "How do I keep their memory alive without staying stuck in the loss?"
   ]
  },
  {
   "name": "Trauma & safety",
   "keywords": [
    "trauma",
    "traumatic",
    "ptsd",
    "flashback",
    "flashbacks",
    "triggered",
    "trigger",
    "abuse",
    "abused",
    "abusive",
    "assault",
    "assaulted",
    "attacked",
    "violence",
    "violent",
    "unsafe",
    "not safe",
    "hypervigilant",
    "on guard",
    "jumpy",
    "startle",
    "dissociate",
    "dissociating",
    "zoned out",
    "shut down",
    "freeze",
    "accident",
    "nightmare about",
    "it happened again",
    "what happened to me",
    "can't talk about it",
    "cant talk about it"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Use 5-4-3-2-1 grounding when the past pulls you in",
     "detail": "When you feel triggered or far away, name out loud five things you can see, four you can touch, three you can hear, two you can smell and one you can taste. Finish by saying today's date and where you are. It brings your senses back to the present.",
     "rationale": "{theme} came up {n} times in this session, including moments that sounded like being pulled back into the past."
    },
    {
     "category": "selfCare",
     "title": "Build a short list of things that make you feel safe",
     "detail": "Write five things that reliably help you feel safer: a person, a place, a blanket, a piece of music, a particular smell. Keep the list on your phone and use one item the next time your body goes on alert.",
     "rationale": "You described feeling unsafe or on guard {n} times; having concrete anchors ready matters more than willpower in those moments."
    },
    {
     "category": "nextSession",
     "title": "Agree on a pace for talking about what happened",
     "detail": "You do not have to tell the whole story at once. Next time, ask your therapist to help you set a pace, a signal for when you need to stop, and a way to close the session so you leave feeling steady.",
     "rationale": "{theme} was a central thread today, and going at a pace that feels safe is part of what makes this work."
    }
   ],
   "questions": [
    "Could we work out what my triggers are and what helps me come back when I get pulled in?",
    "How do I know when I am ready to talk about what happened in more detail?",
    "Why does my body react as if it is still happening, even when I know I am safe?"
   ]
  },
  {
   "name": "Health & body",
   "keywords": [
    "health",
    "doctor",
    "hospital",
    "diagnosis",
    "symptom",
    "symptoms",
    "pain",
    "chronic",
    "illness",
    "sick",
    "medication",
    "meds",
    "surgery",
    "appointment",
    "body",
    "weight",
    "eating",
    "food",
    "appetite",
    "exercise",
    "gym",
    "headache",
    "migraine",
    "stomach",
    "nausea",
    "test results",
    "blood test",
    "injury",
    "my body",
    "disability",
    "period",
    "hormones",
    "pregnant",
    "pregnancy"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Do a ten-minute body scan before bed",
     "detail": "Lie down, close your eyes, and move your attention slowly from your toes to the top of your head, noticing each area without trying to change it. Where there is pain or tension, breathe into it for a few breaths and move on. This builds a kinder relationship with a body that has been difficult.",
     "rationale": "{theme} came up {n} times in this session, with a lot of frustration directed at your body."
    },
    {
     "category": "selfCare",
     "title": "Prepare three questions before your next medical appointment",
     "detail": "Write down what you most want to understand, what worries you, and what you would like to happen next. Bring the note and read from it; appointments go faster than you expect and the important questions are the first to be forgotten.",
     "rationale": "You talked about health concerns {n} times; feeling heard by your doctor is often half the relief."
    },
    {
     "category": "reflection",
     "title": "Separate the symptom from the story about the symptom",
     "detail": "The next time a physical feeling worries you, write two columns: what you actually notice in your body, and what you fear it means. Looking at the two side by side often shows how much of the distress comes from the second column.",
     "rationale": "{theme} was a strong thread today, and worry about the body tends to amplify what the body feels."
    }
   ],
   "questions": [
    "Could we look at how my health worries affect my mood and the other way round?",
    "How do I cope with uncertainty while I am waiting for answers from doctors?",
    "What would it look like to take care of my body without punishing it?"
   ]
  },
  {
   "name": "Money",
   "keywords": [
    "money",
    "debt",
    "bills",
    "rent",
    "mortgage",
    "broke",
    "afford",
    "can't afford",
    "cant afford",
    "finances",
    "financial",
    "budget",
    "salary",
    "paycheck",
    "paid",
    "expensive",
    "savings",
    "loan",
    "credit card",
    "overdraft",
    "spending",
    "spend",
    "income",
    "cost",
    "poor",
    "bankrupt",
    "taxes",
    "paying for",
    "financially",
    "provide for"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Write down the actual numbers once",
     "detail": "Set aside thirty minutes with a calm drink and list what comes in, what goes out, and what is owed. Vague money dread is almost always worse than the real figures. Do it just once this week, then put it away.",
     "rationale": "{theme} came up {n} times in this session, mostly as a background worry rather than concrete numbers."
    },
    {
     "category": "reflection",
     "title": "Notice what money means to you beyond the bills",
     "detail": "Finish these sentences in writing: 'Having money means I am...', 'Not having money means I am...', and 'In my family, money was...'. Often the fear is about safety, worth or control more than the balance itself.",
     "rationale": "You brought up money {n} times; the feelings around it are often older than the current situation."
    },
    {
     "category": "selfCare",
     "title": "Pick one small money action and let the rest wait",
     "detail": "Choose a single step you can do in under twenty minutes, such as calling about a bill, cancelling a subscription, or moving a small amount into savings. Do it this week and give yourself credit; momentum matters more than the amount.",
     "rationale": "{theme} was a strong thread today, and one completed action does more for the dread than hours of worrying."
    }
   ],
   "questions": [
    "Could we look at how money stress is affecting my relationships and sleep?",
    "How do I stop money worries from taking over every quiet moment?",
    "Where does my shame about money come from, and how do I loosen it?"
   ]
  },
  {
   "name": "Loneliness",
   "keywords": [
    "lonely",
    "loneliness",
    "alone",
    "isolated",
    "isolation",
    "no friends",
    "no one",
    "nobody",
    "disconnected",
    "left out",
    "excluded",
    "invisible",
    "by myself",
    "on my own",
    "nobody understands",
    "no one understands",
    "no one to talk to",
    "nobody to talk to",
    "don't belong",
    "dont belong",
    "friendship",
    "friends",
    "social",
    "lost touch",
    "drifted apart",
    "withdraw",
    "withdrawing",
    "hermit",
    "shut myself away",
    "cut off"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Send one low-pressure message this week",
     "detail": "Pick a person you have drifted from and send a short, easy message: a photo, a memory, or 'Thought of you today, how are things?' Do not wait to feel confident; connection usually starts with a small, slightly awkward step.",
     "rationale": "{theme} came up {n} times in this session, alongside a wish for more contact."
    },
    {
     "category": "practice",
     "title": "Put yourself in the same room as people once a week",
     "detail": "Choose a recurring, low-stakes place to be around others: a class, a library, a volunteer shift, a weekly walk group. You do not have to talk much at first. Familiar faces in a familiar place is how most adult friendships actually begin.",
     "rationale": "You described feeling alone or disconnected {n} times; regular proximity does more than occasional big efforts."
    },
    {
     "category": "reflection",
     "title": "Write about the difference between alone and lonely",
     "detail": "Note when being on your own felt peaceful this week and when it felt painful. What was different: the time of day, what you were doing, what you were telling yourself? Loneliness often has a schedule, and knowing it helps.",
     "rationale": "{theme} was a strong thread today, and the ache usually has specific moments where it bites hardest."
    }
   ],
   "questions": [
    "Could we look at what gets in the way when I try to reach out to people?",
    "How do I make friends as an adult without it feeling forced?",
    "Why do I feel lonely even when I am around people?"
   ]
  },
  {
   "name": "Habits & substances",
   "keywords": [
    "drinking",
    "drink",
    "drunk",
    "alcohol",
    "wine",
    "beer",
    "hangover",
    "sober",
    "sobriety",
    "relapse",
    "relapsed",
    "weed",
    "cannabis",
    "smoking",
    "smoke",
    "cigarette",
    "vape",
    "vaping",
    "drugs",
    "pills",
    "cocaine",
    "gambling",
    "gamble",
    "binge",
    "bingeing",
    "scrolling",
    "phone addiction",
    "doomscrolling",
    "addiction",
    "addicted",
    "craving",
    "cravings",
    "urge",
    "urges",
    "porn",
    "cut down",
    "cutting down",
    "too much",
    "can't stop",
    "cant stop"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Try urge surfing the next time a craving hits",
     "detail": "When the urge arrives, set a timer for ten minutes and, instead of fighting it, watch it like a wave: notice where you feel it in your body, how strong it is from one to ten, and how it changes. Most urges peak and fade within that window without you having to act.",
     "rationale": "{theme} came up {n} times in this session, including moments where the urge felt automatic."
    },
    {
     "category": "reflection",
     "title": "Track the trigger, not just the habit",
     "detail": "For one week, each time you do the thing you want to change, write three words: where you were, what you felt just before, and what happened right after. By the end of the week the pattern is usually obvious and gives you a place to intervene.",
     "rationale": "You talked about this habit {n} times; knowing what sets it off is the first lever you can actually pull."
    },
    {
     "category": "selfCare",
     "title": "Replace, do not just remove",
     "detail": "Decide what you will do instead at the moment the habit usually happens, and make it easy: a walk after work instead of the first drink, a book by the bed instead of the phone. Removing a habit without filling the gap leaves the gap pulling at you.",
     "rationale": "{theme} was a strong thread today, and the habit is doing a job that something else will need to do."
    }
   ],
   "questions": [
    "Could we look at what this habit does for me, and what else could do the same job?",
    "How do I handle the shame after a slip without it turning into giving up?",
    "Is this something I can manage on my own, or should I get more specialised help?"
   ]
  },
  {
   "name": "Boundaries",
   "keywords": [
    "boundary",
    "boundaries",
    "say no",
    "saying no",
    "can't say no",
    "cant say no",
    "people pleaser",
    "people pleasing",
    "people-pleasing",
    "taken advantage",
    "take advantage",
    "walked over",
    "doormat",
    "guilt trip",
    "guilt-trip",
    "obligated",
    "obligation",
    "resent",
    "overcommitted",
    "too much on my plate",
    "always the one",
    "expect me to",
    "expects me to",
    "pushover",
    "assert",
    "assertive",
    "stand up for myself",
    "let people",
    "my needs",
    "put myself last"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Script one boundary with DEAR MAN before you say it",
     "detail": "Write it out: Describe the situation in facts, Express how you feel, Assert what you want in one sentence, Reinforce why it helps both of you; then stay Mindful of your point, Appear confident, and be willing to Negotiate. Rehearse it out loud twice before the real conversation.",
     "rationale": "{theme} came up {n} times in this session, usually as something you wanted to say but did not."
    },
    {
     "category": "practice",
     "title": "Buy yourself time with 'Let me check and get back to you'",
     "detail": "For the next week, do not answer any request on the spot. Say you will check and reply later, then decide when you are calm whether you actually want to say yes. The pause breaks the automatic agreement that leads to resentment.",
     "rationale": "You mentioned struggling to say no {n} times; the pause is the easiest first step."
    },
    {
     "category": "reflection",
     "title": "Write down what you fear will happen if you say no",
     "detail": "Pick the person it is hardest to set limits with. Finish the sentence 'If I say no to them, then...' as many times as you can. Then look at each fear and ask how likely it really is, and whether you could handle it if it happened.",
     "rationale": "{theme} was a strong thread today, and the fears behind a hard 'no' are usually bigger than the outcome."
    }
   ],
   "questions": [
    "Could we practise saying no to a specific person in a role-play?",
    "How do I set a limit and then cope with the guilt that comes afterwards?",
    "Where did I learn that other people's needs matter more than mine?"
   ]
  },
  {
   "name": "Change & transitions",
   "keywords": [
    "change",
    "changing",
    "transition",
    "moving",
    "moved",
    "relocate",
    "new job",
    "new city",
    "graduated",
    "graduation",
    "retirement",
    "retire",
    "retiring",
    "starting over",
    "fresh start",
    "uncertain",
    "uncertainty",
    "unknown",
    "decision",
    "decide",
    "crossroads",
    "next chapter",
    "big step",
    "leaving",
    "empty nest",
    "turning forty",
    "turning thirty",
    "turning fifty",
    "milestone",
    "adjusting",
    "adjustment",
    "settle in",
    "settling in"
   ],
   "suggestions": [
    {
     "category": "reflection",
     "title": "Do a values check before the next big decision",
     "detail": "List the five things that matter most to you in life, such as closeness, learning, security, freedom or health. Then score each option you are weighing against those five. The option that honours more of your values is usually easier to live with, even when it is harder.",
     "rationale": "{theme} came up {n} times in this session, with a lot of weighing up and not much clarity yet."
    },
    {
     "category": "selfCare",
     "title": "Keep two anchors steady while everything else moves",
     "detail": "Choose two small routines that stay exactly the same through the transition, like a morning coffee ritual or a Sunday call with the same person. Stability in a couple of places makes the rest of the upheaval much easier to absorb.",
     "rationale": "You talked about change {n} times; the body copes better with upheaval when some things stay fixed."
    },
    {
     "category": "reflection",
     "title": "Write what you are leaving behind, not just what is ahead",
     "detail": "Even good changes involve loss. Write a short list of what ends with this transition: a role, a place, people, a version of yourself. Allowing a little sadness about the old chapter tends to free up energy for the new one.",
     "rationale": "{theme} was a strong thread today, and the loss side of change rarely gets its due."
    }
   ],
   "questions": [
    "Could we look at what I am most afraid of losing in this change?",
    "How do I tell the difference between healthy caution and avoiding a decision?",
    "What would help me feel more grounded while things are still unsettled?"
   ]
  },
  {
   "name": "Identity",
   "keywords": [
    "who i am",
    "who am i",
    "identity",
    "myself",
    "my true self",
    "authentic",
    "pretending",
    "pretend",
    "mask",
    "masking",
    "fit in",
    "fitting in",
    "belong",
    "belonging",
    "culture",
    "cultural",
    "religion",
    "religious",
    "faith",
    "queer",
    "gay",
    "lesbian",
    "bisexual",
    "trans",
    "transgender",
    "nonbinary",
    "non-binary",
    "coming out",
    "came out",
    "immigrant",
    "heritage",
    "purpose",
    "meaning",
    "what i want",
    "lost myself",
    "find myself",
    "real me"
   ],
   "suggestions": [
    {
     "category": "reflection",
     "title": "Write a short 'this is me' page with no audience",
     "detail": "On one page, write what you like, what you believe, what you want and what you refuse, without editing for anyone else. Then mark which parts you show freely, which you hide, and with whom. Revisit it in a month and see what has shifted.",
     "rationale": "{theme} came up {n} times in this session, with a sense of not being fully seen."
    },
    {
     "category": "practice",
     "title": "Show one hidden part of yourself to one safe person",
     "detail": "Pick something small you usually keep quiet, such as a taste, an opinion or a part of your story, and share it with the person you trust most this week. Notice what you expected to happen and what actually happened.",
     "rationale": "You spoke about pretending or masking {n} times; being seen in small doses rebuilds the sense that it is safe."
    },
    {
     "category": "reflection",
     "title": "Notice when you feel most like yourself",
     "detail": "For a week, jot down the moments when you feel most at ease in your own skin: the place, the people, the activity. The pattern points to who you are underneath the roles, and to where to spend more of your time.",
     "rationale": "{theme} was a central thread today, and the answer to 'who am I' is usually in those moments."
    }
   ],
   "questions": [
    "Could we look at the parts of me I hide and what I am afraid would happen if people saw them?",
    "How do I hold on to who I am when I am around people who expect me to be different?",
    "What does it mean to live more honestly, in practical terms, for me?"
   ]
  },
  {
   "name": "Parenting",
   "keywords": [
    "my son",
    "my daughter",
    "my kids",
    "my kid",
    "my children",
    "my child",
    "the kids",
    "the baby",
    "toddler",
    "teenager",
    "teen",
    "parenting",
    "being a parent",
    "as a mom",
    "as a mum",
    "as a dad",
    "as a mother",
    "as a father",
    "school",
    "homework",
    "bedtime routine",
    "tantrum",
    "tantrums",
    "daycare",
    "nursery",
    "co-parent",
    "co-parenting",
    "custody",
    "newborn",
    "postpartum",
    "maternity",
    "paternity",
    "bad parent",
    "good parent",
    "mom guilt",
    "mum guilt",
    "dad guilt"
   ],
   "suggestions": [
    {
     "category": "practice",
     "title": "Give one child ten minutes of undivided attention each day",
     "detail": "Pick a time, put your phone in another room, and let your child lead the activity for ten minutes while you simply follow and comment on what they are doing. Ten focused minutes often changes behaviour more than an hour of distracted time.",
     "rationale": "{theme} came up {n} times in this session, including worries about not being present enough."
    },
    {
     "category": "selfCare",
     "title": "Book one hour this week that is only yours",
     "detail": "Arrange cover from a partner, friend or relative and take an hour away from parenting with no errands attached. Patience is a resource that runs out, and you cannot pour from an empty cup, however much you love them.",
     "rationale": "You talked about parenting {n} times, and almost nothing about rest for yourself."
    },
    {
     "category": "reflection",
     "title": "Repair after a rough moment instead of replaying it",
     "detail": "When you lose your temper or get it wrong, go back later and say simply: 'I got frustrated and shouted. That was not okay, and I am sorry. I love you.' Children learn more from a sincere repair than from a parent who never slips.",
     "rationale": "{theme} was a strong thread today, with a lot of guilt about moments that could be repaired rather than replayed."
    }
   ],
   "questions": [
    "Could we look at what I am repeating from my own parents and what I want to do differently?",
    "How do I stay calm with my kids when I am already running on empty?",
    "Is the guilt I feel as a parent telling me something useful, or is it just noise?"
   ]
  }
 ],
 "emotions": [
  {
   "name": "Anxious",
   "valence": -0.7,
   "keywords": [
    "anxious",
    "anxiety",
    "nervous",
    "worried",
    "worry",
    "panic",
    "panicky",
    "on edge",
    "freaking out",
    "freak out",
    "uneasy",
    "jittery",
    "tense",
    "dread",
    "stressed"
   ]
  },
  {
   "name": "Sad",
   "valence": -0.8,
   "keywords": [
    "sad",
    "sadness",
    "unhappy",
    "down",
    "low",
    "blue",
    "tearful",
    "crying",
    "cried",
    "heartbroken",
    "miserable",
    "gloomy",
    "sorrow",
    "grief",
    "upset"
   ]
  },
  {
   "name": "Angry",
   "valence": -0.7,
   "keywords": [
    "angry",
    "anger",
    "mad",
    "furious",
    "rage",
    "livid",
    "pissed",
    "pissed off",
    "irritated",
    "annoyed",
    "resentful",
    "fuming",
    "seething",
    "hostile"
   ]
  },
  {
   "name": "Ashamed",
   "valence": -0.8,
   "keywords": [
    "ashamed",
    "shame",
    "embarrassed",
    "embarrassing",
    "humiliated",
    "humiliating",
    "mortified",
    "disgusted with myself",
    "cringe",
    "exposed",
    "want to hide",
    "wanted to hide"
   ]
  },
  {
   "name": "Guilty",
   "valence": -0.7,
   "keywords": [
    "guilty",
    "guilt",
    "my fault",
    "blame myself",
    "blamed myself",
    "regret",
    "regretted",
    "remorse",
    "should have",
    "shouldn't have",
    "shouldnt have",
    "let them down",
    "let him down",
    "let her down",
    "feel bad about"
   ]
  },
  {
   "name": "Lonely",
   "valence": -0.7,
   "keywords": [
    "lonely",
    "loneliness",
    "alone",
    "isolated",
    "left out",
    "abandoned",
    "disconnected",
    "nobody cares",
    "no one cares",
    "invisible",
    "unwanted",
    "cut off",
    "by myself"
   ]
  },
  {
   "name": "Overwhelmed",
   "valence": -0.7,
   "keywords": [
    "overwhelmed",
    "overwhelming",
    "too much",
    "can't cope",
    "cant cope",
    "drowning",
    "swamped",
    "snowed under",
    "falling apart",
    "losing it",
    "can't keep up",
    "cant keep up",
    "at my limit",
    "breaking point",
    "buried"
   ]
  },
  {
   "name": "Hopeful",
   "valence": 0.8,
   "keywords": [
    "hopeful",
    "hope",
    "optimistic",
    "looking forward",
    "encouraged",
    "encouraging",
    "promising",
    "better days",
    "light at the end",
    "things are looking up",
    "excited",
    "positive about"
   ]
  },
  {
   "name": "Calm",
   "valence": 0.7,
   "keywords": [
    "calm",
    "calmer",
    "peaceful",
    "at peace",
    "relaxed",
    "settled",
    "steady",
    "grounded",
    "serene",
    "quiet inside",
    "at ease",
    "centered",
    "centred",
    "chilled",
    "tranquil"
   ]
  },
  {
   "name": "Proud",
   "valence": 0.8,
   "keywords": [
    "proud",
    "pride",
    "accomplished",
    "achieved",
    "nailed it",
    "did well",
    "did it",
    "pleased with myself",
    "satisfied",
    "i managed",
    "i pulled it off",
    "good about myself"
   ]
  },
  {
   "name": "Grateful",
   "valence": 0.9,
   "keywords": [
    "grateful",
    "gratitude",
    "thankful",
    "appreciate",
    "appreciated",
    "appreciative",
    "lucky",
    "blessed",
    "fortunate",
    "thank you",
    "thanks to",
    "glad that"
   ]
  },
  {
   "name": "Afraid",
   "valence": -0.8,
   "keywords": [
    "afraid",
    "scared",
    "fear",
    "fearful",
    "terrified",
    "terror",
    "frightened",
    "petrified",
    "horrified",
    "spooked",
    "scared to death",
    "scares me",
    "frightening",
    "threatened"
   ]
  },
  {
   "name": "Frustrated",
   "valence": -0.6,
   "keywords": [
    "frustrated",
    "frustrating",
    "frustration",
    "fed up",
    "sick of",
    "tired of",
    "had enough",
    "exasperated",
    "irritating",
    "aggravated",
    "banging my head",
    "going in circles",
    "stuck"
   ]
  },
  {
   "name": "Hurt",
   "valence": -0.7,
   "keywords": [
    "hurt",
    "hurtful",
    "wounded",
    "betrayed",
    "betrayal",
    "rejected",
    "rejection",
    "let down",
    "disappointed",
    "disappointment",
    "stung",
    "crushed",
    "devastated",
    "heartbroken",
    "dismissed"
   ]
  },
  {
   "name": "Numb",
   "valence": -0.5,
   "keywords": [
    "numb",
    "numbness",
    "empty",
    "hollow",
    "nothing",
    "feel nothing",
    "don't feel anything",
    "dont feel anything",
    "flat",
    "detached",
    "zoned out",
    "checked out",
    "going through the motions",
    "autopilot",
    "blank"
   ]
  },
  {
   "name": "Relieved",
   "valence": 0.7,
   "keywords": [
    "relieved",
    "relief",
    "weight off",
    "weight lifted",
    "lighter",
    "phew",
    "finally over",
    "glad it's over",
    "glad its over",
    "unburdened",
    "breathe again",
    "could breathe",
    "let go of"
   ]
  },
  {
   "name": "Confused",
   "valence": -0.3,
   "keywords": [
    "confused",
    "confusing",
    "confusion",
    "don't understand",
    "dont understand",
    "don't know what",
    "dont know what",
    "mixed up",
    "torn",
    "unsure",
    "lost",
    "no idea",
    "can't make sense",
    "cant make sense",
    "puzzled",
    "conflicted"
   ]
  },
  {
   "name": "Exhausted",
   "valence": -0.6,
   "keywords": [
    "exhausted",
    "exhausting",
    "exhaustion",
    "tired",
    "drained",
    "wiped out",
    "worn out",
    "burned out",
    "burnt out",
    "running on empty",
    "no energy",
    "depleted",
    "shattered",
    "knackered",
    "fatigued",
    "dead on my feet"
   ]
  },
  {
   "name": "Motivated",
   "valence": 0.8,
   "keywords": [
    "motivated",
    "motivation",
    "determined",
    "driven",
    "energised",
    "energized",
    "fired up",
    "ready to",
    "inspired",
    "focused",
    "committed",
    "eager",
    "keen to",
    "can't wait to",
    "cant wait to"
   ]
  },
  {
   "name": "Jealous",
   "valence": -0.6,
   "keywords": [
    "jealous",
    "jealousy",
    "envious",
    "envy",
    "resent",
    "resentful",
    "compare myself",
    "comparing myself",
    "why not me",
    "they have everything",
    "wish i had",
    "left behind",
    "insecure about"
   ]
  }
 ],
 "distortions": [
  {
   "name": "All-or-nothing thinking",
   "description": "Seeing things in black and white: if it is not perfect, it feels like a total failure, with no middle ground.",
   "patterns": [
    "always",
    "never",
    "every time",
    "every single time",
    "completely",
    "totally",
    "nothing ever",
    "all the time",
    "not at all",
    "either",
    "ruined",
    "complete waste",
    "total failure",
    "no point at all"
   ],
   "reframe": "Most things live somewhere in the middle. What would this look like on a scale from one to ten, rather than pass or fail?"
  },
  {
   "name": "Overgeneralization",
   "description": "Taking one difficult event and treating it as proof of a pattern that will go on forever.",
   "patterns": [
    "everyone",
    "nobody",
    "no one ever",
    "everybody",
    "this always happens",
    "it always ends",
    "it never works",
    "nothing works",
    "same old",
    "every relationship",
    "every job",
    "people always",
    "people never",
    "it's always me",
    "its always me"
   ],
   "reframe": "One hard experience is real, but it is one data point. What are the times it went differently, even a little?"
  },
  {
   "name": "Catastrophizing",
   "description": "Jumping to the worst possible outcome and treating it as if it is already happening.",
   "patterns": [
    "what if",
    "worst case",
    "the worst",
    "disaster",
    "catastrophe",
    "it'll be a disaster",
    "fall apart",
    "going to lose everything",
    "end of the world",
    "i can't handle",
    "i cant handle",
    "i won't survive",
    "i wont survive",
    "unbearable",
    "terrible"
   ],
   "reframe": "The worst case is one of many possibilities. What is the most likely outcome, and how would you cope even if the hard version happened?"
  },
  {
   "name": "Mind reading",
   "description": "Assuming you know what someone else is thinking about you, usually something negative, without checking.",
   "patterns": [
    "they think i",
    "he thinks i",
    "she thinks i",
    "they must think",
    "they probably think",
    "everyone thinks",
    "i know they",
    "i know he",
    "i know she",
    "they're judging",
    "theyre judging",
    "judging me",
    "they don't like me",
    "they dont like me",
    "she hates me",
    "he hates me",
    "they hate me"
   ],
   "reframe": "You cannot see inside anyone's head. What is the actual evidence, and what would happen if you asked them directly?"
  },
  {
   "name": "Should statements",
   "description": "Running life by rigid rules about how you or others must behave, which leaves guilt when the rules are broken.",
   "patterns": [
    "i should",
    "i must",
    "i have to",
    "i ought to",
    "i'm supposed to",
    "im supposed to",
    "i should have",
    "i shouldn't",
    "i shouldnt",
    "they should",
    "he should",
    "she should",
    "should be able to",
    "supposed to be"
   ],
   "reframe": "Try swapping 'should' for 'I would like to' or 'it would help if'. The goal stays, the pressure drops."
  },
  {
   "name": "Labeling",
   "description": "Attaching a harsh global label to yourself or someone else based on one behaviour or mistake.",
   "patterns": [
    "i'm such a",
    "im such a",
    "i'm a failure",
    "im a failure",
    "i'm an idiot",
    "im an idiot",
    "i'm a loser",
    "im a loser",
    "i'm useless",
    "im useless",
    "i'm pathetic",
    "im pathetic",
    "i'm a bad",
    "im a bad",
    "i'm stupid",
    "im stupid",
    "he's a narcissist",
    "she's a narcissist",
    "i'm a mess",
    "im a mess"
   ],
   "reframe": "A label describes a whole person from one moment. What did you actually do, and what would a fairer description be?"
  },
  {
   "name": "Personalization",
   "description": "Taking responsibility for things that were not fully, or at all, within your control.",
   "patterns": [
    "my fault",
    "all my fault",
    "because of me",
    "i caused",
    "i ruined",
    "if only i had",
    "if i hadn't",
    "if i hadnt",
    "i let everyone down",
    "i'm the reason",
    "im the reason",
    "i should have known",
    "i made them",
    "i made him",
    "i made her"
   ],
   "reframe": "Draw a pie chart of everything that contributed to this. How big is your slice really, once the other factors are in?"
  },
  {
   "name": "Emotional reasoning",
   "description": "Treating a feeling as proof of a fact: because it feels true, it must be true.",
   "patterns": [
    "i feel like a",
    "i feel like i'm",
    "i feel like im",
    "i feel like nobody",
    "i feel like everyone",
    "i feel like it's",
    "i feel like its",
    "i feel worthless",
    "i feel like a burden",
    "feels hopeless",
    "i feel like a failure",
    "i feel stupid",
    "i feel like nothing"
   ],
   "reframe": "Feelings are real, but they are not always accurate reporters. What would you conclude if you looked only at the facts?"
  },
  {
   "name": "Discounting the positive",
   "description": "Brushing off good things as luck, flukes, or 'not counting', so they never balance the hard things.",
   "patterns": [
    "doesn't count",
    "doesnt count",
    "that doesn't count",
    "just luck",
    "got lucky",
    "anyone could have",
    "it was nothing",
    "no big deal",
    "it's not a big deal",
    "they were just being nice",
    "just being polite",
    "only because",
    "not really an achievement",
    "doesn't mean anything",
    "doesnt mean anything"
   ],
   "reframe": "If a friend had done the same thing, would you dismiss it? Let the good things count at face value, just as the hard ones do."
  },
  {
   "name": "Fortune telling",
   "description": "Predicting that things will turn out badly and reacting as if the prediction is a certainty.",
   "patterns": [
    "it's going to go wrong",
    "its going to go wrong",
    "it's going to fail",
    "its going to fail",
    "i'm going to fail",
    "im going to fail",
    "it won't work",
    "it wont work",
    "it'll never",
    "itll never",
    "i'll never",
    "ill never",
    "there's no way",
    "theres no way",
    "i know it won't",
    "i know it wont",
    "bound to fail",
    "it's not going to",
    "its not going to",
    "won't get better",
    "wont get better"
   ],
   "reframe": "The future is not written yet. What are two other ways this could go, and what small step would nudge it toward one of them?"
  }
 ],
 "commitmentPatterns": [
  "i will",
  "i'll",
  "ill try",
  "i'm going to",
  "im going to",
  "going to try",
  "try to",
  "i'll try",
  "i am going to",
  "homework",
  "practice",
  "practise",
  "before next session",
  "before our next session",
  "next week i",
  "this week i",
  "my goal",
  "commit to",
  "committing to",
  "plan to",
  "planning to",
  "i want to start",
  "i need to",
  "i should start",
  "i'm going to start",
  "im going to start",
  "i'll start",
  "ill start",
  "i promise",
  "i'll make sure",
  "ill make sure",
  "i'm going to try",
  "im going to try",
  "i can try",
  "let me try",
  "i'll give it a go",
  "ill give it a go",
  "from now on",
  "starting tomorrow",
  "starting today",
  "i'll work on",
  "ill work on",
  "i'm going to work on",
  "im going to work on",
  "i'll do",
  "ill do",
  "i will do",
  "i agree to",
  "i'd like to try",
  "id like to try",
  "going to do",
  "i'll practice",
  "ill practice",
  "i'll practise",
  "ill practise"
 ],
 "crisisPatterns": [
  "kill myself",
  "killing myself",
  "end my life",
  "ending my life",
  "take my life",
  "take my own life",
  "suicid",
  "don't want to be alive",
  "dont want to be alive",
  "don't want to live",
  "dont want to live",
  "do not want to live",
  "do not want to be alive",
  "better off dead",
  "better off without me",
  "hurt myself",
  "hurting myself",
  "harm myself",
  "harming myself",
  "self-harm",
  "self harm",
  "selfharm",
  "cutting myself",
  "cut myself",
  "burn myself",
  "burning myself",
  "overdose",
  "overdosing",
  "no reason to live",
  "nothing to live for",
  "end it all",
  "ending it all",
  "end everything",
  "not be here anymore",
  "not being here anymore",
  "not around anymore",
  "want to die",
  "wanted to die",
  "wanting to die",
  "wish i was dead",
  "wish i were dead",
  "wish i wasn't here",
  "wish i wasnt here",
  "wish i wasn't alive",
  "wish i wasnt alive",
  "wish i'd never been born",
  "wish id never been born",
  "wish i would die",
  "wish i could die",
  "wish i could disappear",
  "disappear forever",
  "go to sleep and not wake up",
  "not wake up",
  "never wake up",
  "can't go on",
  "cant go on",
  "can't do this anymore",
  "cant do this anymore",
  "everyone would be better off",
  "they'd be better off without me",
  "theyd be better off without me",
  "world would be better without me",
  "thinking about dying",
  "thoughts of dying",
  "thoughts of death",
  "thinking about death",
  "thought about ending",
  "ways to die",
  "how to die",
  "plan to die",
  "a plan to end",
  "jump off",
  "hang myself",
  "hanging myself",
  "pills to end",
  "slit my wrists",
  "slitting my wrists",
  "stop existing",
  "not exist anymore",
  "want it to be over",
  "want everything to stop",
  "life isn't worth",
  "life isnt worth",
  "not worth living"
 ],
 "positiveWords": [
  "good",
  "great",
  "better",
  "best",
  "well",
  "fine",
  "okay",
  "nice",
  "happy",
  "happier",
  "happiness",
  "joy",
  "joyful",
  "glad",
  "pleased",
  "pleasant",
  "love",
  "loved",
  "loving",
  "like",
  "liked",
  "enjoy",
  "enjoyed",
  "enjoyable",
  "fun",
  "laugh",
  "laughed",
  "laughing",
  "smile",
  "smiled",
  "calm",
  "calmer",
  "peace",
  "peaceful",
  "relax",
  "relaxed",
  "relaxing",
  "rest",
  "rested",
  "restful",
  "safe",
  "safer",
  "secure",
  "comfort",
  "comfortable",
  "ease",
  "easy",
  "easier",
  "hope",
  "hopeful",
  "optimistic",
  "positive",
  "bright",
  "light",
  "lighter",
  "relief",
  "relieved",
  "free",
  "freedom",
  "strong",
  "stronger",
  "strength",
  "brave",
  "courage",
  "confident",
  "confidence",
  "proud",
  "pride",
  "capable",
  "able",
  "success",
  "successful",
  "succeed",
  "achieve",
  "achieved",
  "achievement",
  "accomplish",
  "accomplished",
  "progress",
  "improve",
  "improved",
  "improving",
  "improvement",
  "grow",
  "growth",
  "growing",
  "heal",
  "healed",
  "healing",
  "recover",
  "recovered",
  "recovery",
  "grateful",
  "gratitude",
  "thankful",
  "appreciate",
  "appreciated",
  "kind",
  "kindness",
  "gentle",
  "warm",
  "warmth",
  "care",
  "cared",
  "caring",
  "support",
  "supported",
  "supportive",
  "help",
  "helped",
  "helpful",
  "connect",
  "connected",
  "connection",
  "close",
  "closer",
  "trust",
  "trusted",
  "friend",
  "friendly",
  "together",
  "belong",
  "welcome",
  "welcomed",
  "understood",
  "understanding",
  "heard",
  "seen",
  "accepted",
  "acceptance",
  "worthy",
  "deserve",
  "deserving",
  "enough",
  "motivated",
  "motivation",
  "energy",
  "energetic",
  "excited",
  "excitement",
  "inspired",
  "inspiring",
  "interested",
  "interesting",
  "curious",
  "meaningful",
  "meaning",
  "purpose",
  "wonderful",
  "amazing",
  "beautiful",
  "lovely",
  "excellent",
  "fantastic",
  "perfect",
  "brilliant",
  "awesome",
  "delighted",
  "cheerful",
  "content",
  "satisfied",
  "satisfying",
  "fulfilled",
  "fulfilling",
  "steady",
  "stable",
  "grounded",
  "balanced",
  "clear",
  "clarity",
  "focused",
  "productive",
  "manageable",
  "manage",
  "managed",
  "coping",
  "cope",
  "handle",
  "handled",
  "thrive",
  "thriving",
  "win",
  "won",
  "gift",
  "lucky",
  "blessed",
  "celebrate",
  "celebrated",
  "yes",
  "thanks",
  "thank",
  "healthy",
  "fresh",
  "renewed",
  "forgive",
  "forgave",
  "forgiveness",
  "patient",
  "patience",
  "honest",
  "honesty",
  "proudly",
  "softer",
  "soothing",
  "soothe",
  "reassured",
  "reassuring",
  "encouraged",
  "encouraging",
  "worthwhile",
  "alright"
 ],
 "negativeWords": [
  "bad",
  "worse",
  "worst",
  "terrible",
  "awful",
  "horrible",
  "horrific",
  "dreadful",
  "sad",
  "sadness",
  "unhappy",
  "miserable",
  "misery",
  "depressed",
  "depressing",
  "depression",
  "down",
  "low",
  "hopeless",
  "hopelessness",
  "helpless",
  "helplessness",
  "worthless",
  "useless",
  "pointless",
  "meaningless",
  "empty",
  "emptiness",
  "numb",
  "hollow",
  "lonely",
  "loneliness",
  "alone",
  "isolated",
  "abandoned",
  "rejected",
  "rejection",
  "unwanted",
  "unloved",
  "hurt",
  "hurting",
  "pain",
  "painful",
  "ache",
  "aching",
  "suffer",
  "suffering",
  "cry",
  "cried",
  "crying",
  "tears",
  "tearful",
  "anxious",
  "anxiety",
  "worry",
  "worried",
  "worrying",
  "nervous",
  "panic",
  "panicked",
  "panicking",
  "fear",
  "fearful",
  "afraid",
  "scared",
  "scary",
  "terrified",
  "terrifying",
  "dread",
  "dreading",
  "stress",
  "stressed",
  "stressful",
  "overwhelmed",
  "overwhelming",
  "exhausted",
  "exhausting",
  "exhaustion",
  "tired",
  "drained",
  "burnout",
  "angry",
  "anger",
  "mad",
  "furious",
  "rage",
  "irritated",
  "irritating",
  "annoyed",
  "annoying",
  "frustrated",
  "frustrating",
  "frustration",
  "resentful",
  "resentment",
  "bitter",
  "hate",
  "hated",
  "hateful",
  "disgust",
  "disgusted",
  "disgusting",
  "ashamed",
  "shame",
  "shameful",
  "embarrassed",
  "embarrassing",
  "humiliated",
  "humiliating",
  "guilty",
  "guilt",
  "regret",
  "regretful",
  "blame",
  "blamed",
  "fault",
  "failure",
  "failed",
  "failing",
  "fail",
  "mistake",
  "mistakes",
  "wrong",
  "stupid",
  "idiot",
  "pathetic",
  "weak",
  "weakness",
  "broken",
  "damaged",
  "ruined",
  "destroyed",
  "lost",
  "stuck",
  "trapped",
  "suffocating",
  "drowning",
  "struggle",
  "struggling",
  "struggled",
  "hard",
  "harder",
  "difficult",
  "difficulty",
  "impossible",
  "unbearable",
  "crisis",
  "problem",
  "problems",
  "trouble",
  "troubled",
  "disaster",
  "nightmare",
  "dark",
  "darkness",
  "heavy",
  "burden",
  "burdened",
  "sick",
  "ill",
  "illness",
  "unwell",
  "disease",
  "insomnia",
  "sleepless",
  "dying",
  "death",
  "died",
  "dead",
  "grief",
  "grieving",
  "loss",
  "mourning",
  "abuse",
  "abused",
  "abusive",
  "trauma",
  "traumatic",
  "attack",
  "attacked",
  "violent",
  "violence",
  "threat",
  "threatened",
  "unsafe",
  "danger",
  "dangerous",
  "cruel",
  "cruelty",
  "harsh",
  "toxic",
  "betrayed",
  "betrayal",
  "cheated",
  "lied",
  "liar",
  "fight",
  "fighting",
  "argue",
  "argument",
  "conflict",
  "shouting",
  "yelling",
  "screaming",
  "ignored",
  "dismissed",
  "criticized",
  "criticised",
  "criticism",
  "judged",
  "judgment",
  "judgement",
  "jealous",
  "jealousy",
  "envy",
  "envious",
  "insecure",
  "insecurity",
  "doubt",
  "doubts",
  "confused",
  "confusing",
  "confusion",
  "uncertain",
  "uncertainty",
  "unsure",
  "nothing",
  "never",
  "no",
  "not",
  "can't",
  "cant",
  "won't",
  "wont",
  "don't",
  "dont",
  "disappointed",
  "disappointing",
  "disappointment",
  "upset",
  "upsetting",
  "distressed",
  "distressing",
  "distress",
  "desperate",
  "desperation",
  "despair",
  "agony",
  "torment",
  "tormented",
  "wreck",
  "mess",
  "messed",
  "chaos",
  "chaotic",
  "collapse",
  "collapsed",
  "crash",
  "crashed",
  "withdrawn",
  "avoid",
  "avoiding",
  "avoidance",
  "shut",
  "shutdown",
  "cold",
  "distant",
  "neglected",
  "neglect",
  "ugly",
  "fat",
  "gross",
  "loser",
  "coward",
  "paralyzed",
  "paralysed",
  "frozen",
  "froze",
  "shaking",
  "trembling",
  "sweating",
  "nauseous",
  "sob",
  "sobbing",
  "miserably",
  "unfair",
  "unfairness",
  "injustice",
  "powerless",
  "victim"
 ],
 "stopWords": [
  "a",
  "an",
  "the",
  "and",
  "or",
  "but",
  "if",
  "then",
  "else",
  "so",
  "because",
  "as",
  "of",
  "at",
  "by",
  "for",
  "with",
  "about",
  "against",
  "between",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "to",
  "from",
  "up",
  "down",
  "in",
  "out",
  "on",
  "off",
  "over",
  "under",
  "again",
  "further",
  "once",
  "here",
  "there",
  "when",
  "where",
  "why",
  "how",
  "all",
  "any",
  "both",
  "each",
  "few",
  "more",
  "most",
  "other",
  "some",
  "such",
  "no",
  "nor",
  "not",
  "only",
  "own",
  "same",
  "than",
  "too",
  "very",
  "s",
  "t",
  "can",
  "will",
  "just",
  "don",
  "should",
  "now",
  "i",
  "me",
  "my",
  "myself",
  "we",
  "our",
  "ours",
  "ourselves",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "what",
  "which",
  "who",
  "whom",
  "this",
  "that",
  "these",
  "those",
  "am",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "doing",
  "would",
  "could",
  "might",
  "must",
  "shall",
  "may",
  "ought",
  "im",
  "i'm",
  "ive",
  "i've",
  "id",
  "i'd",
  "ill",
  "i'll",
  "youre",
  "you're",
  "youve",
  "you've",
  "youll",
  "you'll",
  "youd",
  "you'd",
  "hes",
  "he's",
  "shes",
  "she's",
  "it's",
  "we're",
  "weve",
  "we've",
  "well",
  "we'll",
  "wed",
  "we'd",
  "theyre",
  "they're",
  "theyve",
  "they've",
  "theyll",
  "they'll",
  "theyd",
  "they'd",
  "thats",
  "that's",
  "whats",
  "what's",
  "whos",
  "who's",
  "theres",
  "there's",
  "heres",
  "here's",
  "wheres",
  "where's",
  "hows",
  "how's",
  "dont",
  "don't",
  "doesnt",
  "doesn't",
  "didnt",
  "didn't",
  "cant",
  "can't",
  "cannot",
  "couldnt",
  "couldn't",
  "wont",
  "won't",
  "wouldnt",
  "wouldn't",
  "shouldnt",
  "shouldn't",
  "isnt",
  "isn't",
  "arent",
  "aren't",
  "wasnt",
  "wasn't",
  "werent",
  "weren't",
  "hasnt",
  "hasn't",
  "havent",
  "haven't",
  "hadnt",
  "hadn't",
  "mustnt",
  "mustn't",
  "lets",
  "let's",
  "gonna",
  "wanna",
  "gotta",
  "yeah",
  "yes",
  "yep",
  "nope",
  "okay",
  "ok",
  "oh",
  "ah",
  "hmm",
  "mm",
  "mhm",
  "huh",
  "right",
  "really",
  "actually",
  "basically",
  "literally",
  "maybe",
  "perhaps",
  "probably",
  "definitely",
  "sort",
  "kind",
  "lot",
  "lots",
  "thing",
  "things",
  "something",
  "anything",
  "everything",
  "someone",
  "anyone",
  "everyone",
  "one",
  "ones",
  "also",
  "even",
  "still",
  "yet",
  "already",
  "always",
  "never",
  "ever",
  "often",
  "sometimes",
  "usually",
  "much",
  "many",
  "little",
  "less",
  "least",
  "quite",
  "rather",
  "pretty",
  "almost",
  "around",
  "away",
  "back",
  "like",
  "get",
  "got",
  "gets",
  "getting",
  "go",
  "goes",
  "going",
  "went",
  "gone",
  "come",
  "comes",
  "coming",
  "came",
  "make",
  "makes",
  "making",
  "made",
  "take",
  "takes",
  "taking",
  "took",
  "say",
  "says",
  "saying",
  "said",
  "know",
  "knows",
  "knowing",
  "knew",
  "think",
  "thinks",
  "thinking",
  "thought",
  "mean",
  "means",
  "meaning",
  "meant",
  "see",
  "sees",
  "seeing",
  "saw",
  "want",
  "wants",
  "wanted",
  "need",
  "needs",
  "needed",
  "let",
  "put",
  "tell",
  "told",
  "ask",
  "asked",
  "way",
  "ways",
  "time",
  "times",
  "day",
  "days",
  "week",
  "weeks",
  "year",
  "years",
  "today",
  "yesterday",
  "tomorrow",
  "tonight",
  "last",
  "next",
  "first",
  "second",
  "new",
  "old",
  "big",
  "small",
  "long",
  "short",
  "every",
  "while",
  "since",
  "until",
  "till",
  "though",
  "although",
  "whether",
  "either",
  "neither",
  "whatever",
  "whenever",
  "wherever",
  "however",
  "anyway",
  "anyways",
  "mine",
  "us",
  "ya",
  "y'all",
  "yall",
  "em",
  "en",
  "re",
  "ve",
  "ll",
  "d",
  "m",
  "o",
  "n't",
  "'s",
  "'t",
  "'re",
  "'ve",
  "'ll",
  "'d",
  "'m"
 ],
 "fillerWords": [
  "um",
  "umm",
  "uh",
  "uhh",
  "er",
  "erm",
  "ah",
  "ahh",
  "eh",
  "hmm",
  "hm",
  "mm",
  "mhm",
  "like",
  "you know",
  "i mean",
  "kind of",
  "kinda",
  "sort of",
  "sorta",
  "basically",
  "literally",
  "actually",
  "honestly",
  "obviously",
  "right",
  "okay so",
  "ok so",
  "so yeah",
  "yeah so",
  "well",
  "anyway",
  "anyways",
  "whatever",
  "stuff",
  "things like that",
  "or whatever",
  "and stuff",
  "and things",
  "you see",
  "i guess",
  "i suppose",
  "just",
  "really",
  "totally",
  "pretty much",
  "at the end of the day",
  "to be honest",
  "to be fair",
  "if that makes sense",
  "does that make sense",
  "know what i mean",
  "you know what i mean",
  "i don't know",
  "i dont know",
  "i dunno",
  "dunno",
  "la",
  "yeah",
  "yep",
  "yup",
  "nah",
  "huh",
  "ooh",
  "oh",
  "gosh",
  "jeez"
 ],
 "generalSuggestions": [
  {
   "category": "reflection",
   "title": "Write three lines about how this session landed",
   "detail": "Within a few hours, while it is still fresh, jot down what stayed with you, what surprised you, and one thing you want to remember. Three lines is enough; the aim is to keep the thread alive between sessions.",
   "rationale": "Sessions fade fast. A short note the same day roughly doubles what you keep."
  },
  {
   "category": "practice",
   "title": "Re-read your commitments midweek",
   "detail": "Set a reminder for the middle of the week to open this session's action items. Tick off what you did, and for anything you did not, write one line about what got in the way rather than judging yourself.",
   "rationale": "A midweek check is where good intentions turn into things that actually happened."
  },
  {
   "category": "reflection",
   "title": "Notice one moment this week when the old pattern shows up",
   "detail": "You do not have to change anything yet. Just catch the pattern you talked about once, in real time, and write down the situation, the thought and the feeling. Noticing is the first half of change.",
   "rationale": "You talked about a pattern today, and seeing it as it happens is more useful than analysing it afterwards."
  },
  {
   "category": "selfCare",
   "title": "Schedule the next session while it is fresh",
   "detail": "Book or confirm the next appointment today, and put it in your calendar with a 24-hour reminder. Gaps that grow by accident are the most common reason progress stalls.",
   "rationale": "Regular rhythm matters more than any single session."
  },
  {
   "category": "practice",
   "title": "Pick one suggestion, not five",
   "detail": "Choose the single idea from this session that feels most doable, and leave the rest for another week. Doing one thing fully builds more confidence than half-starting several.",
   "rationale": "Too many changes at once is the surest way to make none of them."
  },
  {
   "category": "nextSession",
   "title": "Bring one question you did not get to ask",
   "detail": "Look at the questions saved from this session and pick the one that matters most, or write a new one. Say it in the first five minutes next time, before the session fills up with the week's events.",
   "rationale": "The things that matter most are often the ones that get crowded out."
  },
  {
   "category": "selfCare",
   "title": "Do something kind for your body today",
   "detail": "Therapy is work, and the body carries it. Today, take a slow walk, stretch for five minutes, eat a proper meal, or go to bed thirty minutes earlier than usual. Nothing heroic, just a small signal that you are on your own side.",
   "rationale": "After a demanding session, a little physical care helps everything settle."
  },
  {
   "category": "reflection",
   "title": "Rate how useful this session felt and why",
   "detail": "Give the session a score from one to ten and write one sentence about what made it that number. Share the score with your therapist next time; it is one of the most useful pieces of feedback they can get.",
   "rationale": "Therapy works best as a collaboration, and honest feedback steers it."
  }
 ],
 "supportResources": [
  {
   "title": "If you are in the US",
   "detail": "Call or text 988 to reach the 988 Suicide & Crisis Lifeline, any time, day or night."
  },
  {
   "title": "If you are in the UK or Ireland",
   "detail": "Call Samaritans free on 116 123, any time, from any phone."
  },
  {
   "title": "Elsewhere",
   "detail": "Call your local emergency number, or find a helpline for your country at findahelpline.com."
  },
  {
   "title": "Tell someone you trust",
   "detail": "Reach out to your therapist, a friend, or a family member and tell them how you are feeling. You do not have to carry this alone."
  },
  {
   "title": "If you are in immediate danger",
   "detail": "Call your local emergency services right now, or go to the nearest emergency department."
  }
 ]
};
